### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: The response is not a valid JSON string:

### ISSUE THREAD

**Issue by geekspeng** [nexmark/nexmark#25]
root@nexmark01:~# nexmark/bin/run_query.sh q0
Benchmark Queries: [q0]
==================================================================
Start to run query q0 with workload [tps=10 M, eventsNum=100 M, percentage=bid:46,auction:3,person:1,kafkaServers:null]
Exception in thread "main" java.lang.RuntimeException: The response is not a valid JSON string:
{"jobs":[{"id":"278cd89700643e469a60068b7eca0a2c","status":"RESTARTING"}]}
	at com.github.nexmark.flink.metric.FlinkRestClient.getCurrentJobId(FlinkRestClient.java:100)
	at com.github.nexmark.flink.QueryRunner.run(QueryRunner.java:70)
	at com.github.nexmark.flink.Benchmark.runQueries(Benchmark.java:126)
	at com.github.nexmark.flink.Benchmark.main(Benchmark.java:77)
Caused by: java.lang.IllegalArgumentException: The first job is not running.
	at org.apache.flink.util.Preconditions.checkArgument(Preconditions.java:138)
	at com.github.nexmark.flink.metric.FlinkRestClient.getCurrentJobId(FlinkRestClient.java:95)
	... 3 more

====================环境如下================
root@nexmark01:~# java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-8u312-b07-0ubuntu1~20.04-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)
root@nexmark01:~#

Flink 版本 1.14.3
https://mirrors.aliyun.com/apache/flink/flink-1.14.3/flink-1.14.3-bin-scala_2.12.tgz

**Comment by geekspeng** [comment]
can be solved by following steps
1. flink/bin/stop-cluster.sh
2. nexmark/bin/shutdown_cluster.sh
3. link/bin/start-cluster.sh
4. nexmark/bin/setup_cluster.sh

**Comment by guangzegu** [comment]
Flink 1.13.0和1.13.6也出现同样的错误

**Comment by Zakelly** [comment]
这个其实是由于nexmark runner没考虑到错误恢复的情况。可以先看下flink ui上面为什么query job进入了重启的情况。

**Comment by Zakelly** [comment]
> 我们测试也碰到类似的错误，nexmark好像只检查第一个job的状态，而且没有处理cancel,finished等情况，打开warmup后特别容易出现这种情况。

@kuaiwei 如果你用的是比较新的版本，包括小版本，flink client有改过这个job顺序，所以第一个job状态不一定就是当前job。可以试用一下这个pr：https://github.com/nexmark/nexmark/pull/27

如果是job出错等问题，后面我会提交一个pr增加测试流程鲁棒性
