### ISSUE TITLE
no metrics but jobs completed while querying q3 

### ISSUE THREAD

**Issue by yufishyou** [nexmark/nexmark#44]
WARN  com.github.nexmark.flink.metric.MetricReporter               [] - Job metric is not ready yet.
java.lang.RuntimeException: Can't find TPS metric name from the response:
[]
        at com.github.nexmark.flink.metric.FlinkRestClient.getTpsMetricName(FlinkRestClient.java:165) ~[nexmark-flink-0.2-SNAPSHOT.jar:?]
        at com.github.nexmark.flink.metric.MetricReporter.getJobInformation(MetricReporter.java:96) [nexmark-flink-0.2-SNAPSHOT.jar:?]

how to fix it？

**Comment by Sunt-ing** [comment]
+1. No idea how to fix it.

**Comment by maxb-io** [comment]
I see the same problem, this is the warning in the nexmark-flink.log:

2023-06-19 10:25:17,606 WARN  com.github.nexmark.flink.metric.MetricReporter               [] - Job metric is not ready yet.
java.lang.RuntimeException: Can't find TPS metric name from the response:
[]
        at com.github.nexmark.flink.metric.FlinkRestClient.getTpsMetricName(FlinkRestClient.java:165) ~[nexmark-flink-0.2-SNAPSHOT.jar:?]
        at com.github.nexmark.flink.metric.MetricReporter.getJobInformation(MetricReporter.java:96) [nexmark-flink-0.2-SNAPSHOT.jar:?]
        at com.github.nexmark.flink.metric.MetricReporter.submitMonitorThread(MetricReporter.java:70) [nexmark-flink-0.2-SNAPSHOT.jar:?]
        at com.github.nexmark.flink.metric.MetricReporter.reportMetric(MetricReporter.java:140) [nexmark-flink-0.2-SNAPSHOT.jar:?]
        at com.github.nexmark.flink.QueryRunner.run(QueryRunner.java:85) [nexmark-flink-0.2-SNAPSHOT.jar:?]
        at com.github.nexmark.flink.Benchmark.executeQueries(Benchmark.java:202) [nexmark-flink-0.2-SNAPSHOT.jar:?]
        at com.github.nexmark.flink.Benchmark.runQueries(Benchmark.java:109) [nexmark-flink-0.2-SNAPSHOT.jar:?]
        at com.github.nexmark.flink.Benchmark.main(Benchmark.java:81) [nexmark-flink-0.2-SNAPSHOT.jar:?]
2023-06-19 10:25:18,665 WARN  com.github.nexmark.flink.metric.cpu.CpuMetricReceiver        [] - The cpu metric receiver doesn't receive any metrics.
2023-06-19 10:25:18,666 INFO  com.github.nexmark.flink.metric.MetricReporter               [] - Current Cores=0 (0 TMs)
----------------------------------------------------------------------------------------------------------------
and this is the exception from run_query.sh:

 nexmark/bin/run_query.sh all
Benchmark Queries: [q0, q1, q2, q3, q4, q5, q7, q8, q9, q10, q11, q12, q13, q14, q15, q16, q17, q18, q19, q20, q21, q22]
==================================================================
Start to run query q0 with workload [tps=10 M, eventsNum=1 G, percentage=bid:46,auction:3,person:1,kafkaServers:null]
Start the warmup for at most 120000ms and 100000000 events.
Stop the warmup, cost 100ms.
Monitor metrics after 60 seconds.
Start to monitor metrics until job is finished.
Exception in thread "main" java.lang.RuntimeException: The metric reporter doesn't collect any metrics.
        at com.github.nexmark.flink.metric.MetricReporter.reportMetric(MetricReporter.java:153)
        at com.github.nexmark.flink.QueryRunner.run(QueryRunner.java:85)
        at com.github.nexmark.flink.Benchmark.executeQueries(Benchmark.java:202)
        at com.github.nexmark.flink.Benchmark.runQueries(Benchmark.java:109)
        at com.github.nexmark.flink.Benchmark.main(Benchmark.java:81)
Current Cores=0 (0 TMs)
--------------------------------------------------------------------------------------------------------------
As suggested by @ExplorerXP I tried to set:
nexmark.metric.monitor.delay: 1min
nexmark.workload.suite.100m.events.num: 1000000000
but with no luck, same exception.

**Comment by ExplorerXP** [comment]
@maxb-io 
set nexmark.metric.monitor.delay to 1s
edit flink/conf/flink.yaml and set taskmanager.numberOfTaskSlots: 1    parallelism.default: 1
try it again

**Comment by maxb-io** [comment]
Thanks @ExplorerXP , I made the changes and now I don't see the exception when the test starts, but still no metrics.
```
 nexmark/bin/run_query.sh all
Benchmark Queries: [q0, q1, q2, q3, q4, q5, q7, q8, q9, q10, q11, q12, q13, q14, q15, q16, q17, q18, q19, q20, q21, q22]
==================================================================
Start to run query q0 with workload [tps=10 M, eventsNum=100 M, percentage=bid:46,auction:3,person:1,kafkaServers:null]
Start the warmup for at most 120000ms and 100000000 events.
Stop the warmup, cost 120100ms.
Monitor metrics after 1 seconds.
Start to monitor metrics until job is finished.
Current Cores=0 (0 TMs)
Current Cores=0 (0 TMs)
Current Cores=0 (0 TMs)
Current Cores=0 (0 TMs)
Current Cores=0 (0 TMs)
Current Cores=0 (0 TMs)
Current Cores=0 (0 TMs)
``` 
In the nexmark-flink.log:

```
2023-06-28 16:12:23,766 WARN  com.github.nexmark.flink.metric.MetricReporter               [] - Job metric is not ready yet.
java.lang.RuntimeException: Can't find TPS metric name from the response:
[]
        at com.github.nexmark.flink.metric.FlinkRestClient.getTpsMetricName(FlinkRestClient.java:165) ~[nexmark-flink-0.2-SNAPSHOT.jar:?]
        at com.github.nexmark.flink.metric.MetricReporter.getJobInformation(MetricReporter.java:96) [nexmark-flink-0.2-SNAPSHOT.jar:?]
        at com.github.nexmark.flink.metric.MetricReporter.submitMonitorThread(MetricReporter.java:70) [nexmark-flink-0.2-SNAPSHOT.jar:?]
        at com.github.nexmark.flink.metric.MetricReporter.reportMetric(MetricReporter.java:140) [nexmark-flink-0.2-SNAPSHOT.jar:?]
        at com.github.nexmark.flink.QueryRunner.run(QueryRunner.java:85) [nexmark-flink-0.2-SNAPSHOT.jar:?]
        at com.github.nexmark.flink.Benchmark.executeQueries(Benchmark.java:202) [nexmark-flink-0.2-SNAPSHOT.jar:?]
        at com.github.nexmark.flink.Benchmark.runQueries(Benchmark.java:109) [nexmark-flink-0.2-SNAPSHOT.jar:?]
        at com.github.nexmark.flink.Benchmark.main(Benchmark.java:81) [nexmark-flink-0.2-SNAPSHOT.jar:?]
2023-06-28 16:12:24,770 WARN  com.github.nexmark.flink.metric.cpu.CpuMetricReceiver        [] - The cpu metric receiver doesn't receive any metrics.
2023-06-28 16:12:24,770 INFO  com.github.nexmark.flink.metric.MetricReporter               [] - Current Cores=0 (0 TMs)
2023-06-28 16:12:29,772 WARN  com.github.nexmark.flink.metric.cpu.CpuMetricReceiver        [] - The cpu metric receiver doesn't receive any metrics.
2023-06-28 16:12:29,772 INFO  com.github.nexmark.flink.metric.MetricReporter               [] - Current Cores=0 (0 TMs)
2023-06-28 16:12:34,774 WARN  com.github.nexmark.flink.metric.cpu.CpuMetricReceiver        [] - The cpu metric receiver doesn't receive any metrics.
2023-06-28 16:12:34,774 INFO  com.github.nexmark.flink.metric.MetricReporter               [] - Current Cores=0 (0 TMs)
2023-06-28 16:12:39,775 WARN  com.github.nexmark.flink.metric.cpu.CpuMetricReceiver        [] - The cpu metric receiver doesn't receive any metr
``` 
These are the custom changes in flink/conf/flink-conf.yaml

```
diff ../flink/conf/flink-conf.yaml ../nexmark/conf/flink-conf.yaml |grep "^<"
< jobmanager.rpc.address: 9.151.1.25
< parallelism.default: 1
< state.checkpoints.dir: file:///data/ubuntu/checkpoint
< state.backend.rocksdb.localdir: /data/rocksdb
< execution.checkpointing.checkpoints-after-tasks-finish.enabled: false
```

**Comment by ExplorerXP** [comment]
On every worker configed in flink/conf/workers， the process ‘CpuMetricSender’ should exist when you call ‘jps’, otherwise, you may need to check your steps against the README.md.  Pay special attention to the console log generated when executing ./nexmark/bin/setup_cluster.sh.

**Comment by yufishyou** [comment]
--I forget my  specific solution but basic steps to solve this is like below :
1.Check if the port is occupied
2.Increase test data
3.Better rerun nexmark while performing every single SQL testing
--Hope it helps.

**Comment by maxb-io** [comment]
Thanks @ExplorerXP and @yufishyou 
Running "cd nexmark/bin/ && ./metric_client.sh start" on each worker node made the trick.
