### ISSUE TITLE
[BUG] java.lang.ArithmeticException: long overflow

### ISSUE THREAD

**Issue by fuuuyuuu** [nexmark/nexmark#48]
Hello,  I am using the `nexmark` to evaluate flink, but met the error although following the tutorial step by step.
could you please give me some advice?
```shell
Exception in thread "main" java.lang.ArithmeticException: long overflow
	at java.lang.Math.multiplyExact(Math.java:892)
	at java.time.Duration.toNanos(Duration.java:1186)
	at org.apache.flink.api.common.time.Deadline.fromNow(Deadline.java:98)
	at com.github.nexmark.flink.metric.MetricReporter.waitForOrJobFinish(MetricReporter.java:124)
	at com.github.nexmark.flink.metric.MetricReporter.reportMetric(MetricReporter.java:165)
	at com.github.nexmark.flink.QueryRunner.run(QueryRunner.java:85)
	at com.github.nexmark.flink.Benchmark.executeQueries(Benchmark.java:202)
	at com.github.nexmark.flink.Benchmark.runQueries(Benchmark.java:109)
	at com.github.nexmark.flink.Benchmark.main(Benchmark.java:81)
```

Description

Steps/Code to Reproduce

Versions
flink version
<img width="278" alt="image" src="https://github.com/nexmark/nexmark/assets/43876761/e1ef3edb-acd0-4964-b4cb-9bf5f679c0df">
java version
<img width="251" alt="image" src="https://github.com/nexmark/nexmark/assets/43876761/de6e4c02-f587-4ca4-97a5-708ecb30c638">
the `nexmark` is download with source code and builded in host.

**Comment by yufishyou** [comment]
I met the same question and naxmark did not stop thus no effective result,I did not meet such problem a month ago
`[root@server1 nexmark-flink]# ./bin/run_query.sh q2
Benchmark Queries: [q2]
==================================================================
Start to run query q2 with workload [tps=100 M, eventsNum=1 G, percentage=bid:46,auction:3,person:1,kafkaServers:null]
Start the warmup for at most 120000ms and 1000000000 events.
Stop the warmup, cost 54400ms.
Monitor metrics after 10 seconds.
Start to monitor metrics until job is finished.
Exception in thread "main" java.lang.ArithmeticException: long overflow
        at java.lang.Math.multiplyExact(Math.java:892)
        at java.time.Duration.toNanos(Duration.java:1186)
        at org.apache.flink.api.common.time.Deadline.fromNow(Deadline.java:98)
        at com.github.nexmark.flink.metric.MetricReporter.waitForOrJobFinish(MetricReporter.java:124)
        at com.github.nexmark.flink.metric.MetricReporter.reportMetric(MetricReporter.java:165)
        at com.github.nexmark.flink.QueryRunner.run(QueryRunner.java:85)
        at com.github.nexmark.flink.Benchmark.executeQueries(Benchmark.java:202)
        at com.github.nexmark.flink.Benchmark.runQueries(Benchmark.java:109)
        at com.github.nexmark.flink.Benchmark.main(Benchmark.java:81)
Current Cores=378.12 (12 TMs)
Current Cores=376.12 (12 TMs)
Current Cores=379.45 (12 TMs)
Current Cores=379.25 (12 TMs)
Current Cores=379.44 (12 TMs)
Current Cores=379.52 (12 TMs)
Current Cores=379.3 (12 TMs)
Current Cores=358.16 (12 TMs)
Current Cores=252.58 (12 TMs)
Current Cores=120.99 (12 TMs)
Current Cores=13.97 (12 TMs)
Current Cores=0.06 (12 TMs)
Current Cores=0.01 (12 TMs)
Current Cores=0.06 (12 TMs)
Current Cores=0.02 (12 TMs)
Current Cores=0.07 (12 TMs)
Current Cores=0.02 (12 TMs)
Current Cores=0.05 (12 TMs)
Current Cores=0.12 (12 TMs)
Current Cores=0.13 (12 TMs)
Current Cores=0.02 (12 TMs)
^C

**Comment by yufishyou** [comment]
I tried the old release one month ago I download ,and it works well

**Comment by fuuuyuuu** [comment]
> yeah, the released version does not have this problem, either. But there is another problem [https://github.com/nexmark/nexmark/pull/27](url) in the released version, so I need to fix it manually.

**Comment by fuuuyuuu** [comment]
And there is a fatal error when we run multiple query in single command, like this:
`bash $NEXMARK_HOME/bin/run_query.sh q0,q1,q2`
it would raise the following error, only the first query will return successfully,
<img width="893" alt="image" src="https://github.com/nexmark/nexmark/assets/43876761/f0453a28-a40c-498d-b595-15b5f06232df">
I notice that in worker node, the **CpuMetricSender** is closed when completed the first query...
